### ISSUE TITLE
Traceback: ValueError: Expected datetime, date, or time

### ISSUE THREAD

**Issue by PepperPhil** [KoljaWindeler/ics#13]
**Issue with Calendar: https://www.abfallkalender-ab.de/cache/ical/Dettingen-2020-1598518537.ics**

============= ICS Integration Error ================
2020-08-27 11:40:16 ERROR (MainThread) [custom_components.ics.sensor] unfortunately ICS hit an error, please open a ticket at
2020-08-27 11:40:16 ERROR (MainThread) [custom_components.ics.sensor] https://github.com/KoljaWindeler/ics/issues
2020-08-27 11:40:16 ERROR (MainThread) [custom_components.ics.sensor] and paste the following output:

2020-08-27 11:40:16 ERROR (MainThread) [custom_components.ics.sensor] Traceback (most recent call last):
  File "/config/custom_components/ics/sensor.py", line 168, in get_data
    cal = Calendar.from_ical(cal_string)
  File "/usr/local/lib/python3.8/site-packages/icalendar/cal.py", line 383, in from_ical
    vals = factory(factory.from_ical(vals))
  File "/usr/local/lib/python3.8/site-packages/icalendar/prop.py", line 347, in from_ical
    raise ValueError(
ValueError: Expected datetime, date, or time, got: '5'

**Comment by KoljaWindeler** [comment]
Hi that link returns a 404 error .. is it possible that the /cache/ links don't work for long? 
Kolja

**Comment by PepperPhil** [comment]
Sorry for the late reply. Yes, I figured out that those links are only created for one time use. :-(
