### ISSUE TITLE
Integration Error

### ISSUE THREAD

**Issue by Jim2506** [KoljaWindeler/ics#24]
Hi Kolja,
I get the following error:
============= ICS Integration Error ================
2021-03-08 12:53:38 ERROR (MainThread) [custom_components.ics.sensor] unfortunately ICS hit an error, please open a ticket at
2021-03-08 12:53:38 ERROR (MainThread) [custom_components.ics.sensor] https://github.com/KoljaWindeler/ics/issues
2021-03-08 12:53:38 ERROR (MainThread) [custom_components.ics.sensor] and paste the following output:
2021-03-08 12:53:38 ERROR (MainThread) [custom_components.ics.sensor] Traceback (most recent call last):
File "/config/custom_components/ics/sensor.py", line 180, in get_data
reoccuring_events = recurring_ical_events.of(cal).between(start_date, end_date)
File "/usr/local/lib/python3.8/site-packages/recurring_ical_events.py", line 374, in of
return UnfoldableCalendar(a_calendar)
File "/usr/local/lib/python3.8/site-packages/recurring_ical_events.py", line 270, in __init__
self.repetitions.append(self.RepeatedEvent(event))
File "/usr/local/lib/python3.8/site-packages/recurring_ical_events.py", line 136, in __init__
self.start = self.original_start = event["DTSTART"].dt
AttributeError: 'NoneType' object has no attribute 'dt'
2021-03-08 12:53:38 ERROR (MainThread) [custom_components.ics.sensor]
thanks, Kolja

The configuration of sensor does not have changed in the last couple of weeks, please find below an example:
- platform: ics
  name: Gelber Sack
  startswith: Abfuhr Leichtstoffe
  url: https://www.voerde.de/abfalltermine-bezirk4.ics
  id: 3
  icon: "mdi:recycle"
  show_remaining: true

**Comment by KoljaWindeler** [comment]
is this working now? works with my setup

**Comment by kmaxk** [comment]
============= ICS Integration Error ================
2021-08-18 10:10:41 ERROR (MainThread) [custom_components.ics.sensor] unfortunately ICS hit an error, please open a ticket at
2021-08-18 10:10:41 ERROR (MainThread) [custom_components.ics.sensor] https://github.com/KoljaWindeler/ics/issues
2021-08-18 10:10:41 ERROR (MainThread) [custom_components.ics.sensor] and paste the following output:
2021-08-18 10:10:41 ERROR (MainThread) [custom_components.ics.sensor] Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "", line 3, in raise_from
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/usr/local/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.9/http/client.py", line 285, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/config/custom_components/ics/sensor.py", line 169, in get_data
    cal_string = await async_load_data(self.hass, self._url)
  File "/config/custom_components/ics/const.py", line 243, in async_load_data
    return await hass.async_add_executor_job(_load_data, url)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ics/const.py", line 239, in _load_data
    return requests.get(url, headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36'}, allow_redirects=True).content
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
thanks, Kolja
2021-08-18 10:10:41 ERROR (MainThread) [custom_components.ics.sensor] ============= ICS Integration Error ================

hi Kolja,
still got this error on 0.6.1.

**Comment by KoljaWindeler** [comment]
hmm is you installation online? looks like the connection can't be established at all ... 

BTW: dein Kalender sagt bei mir das dein Restmüll morgen abgeholt wird :D
