### ISSUE TITLE
local file is not getting imported

### ISSUE THREAD

**Issue by BKneer** [KoljaWindeler/ics#49]
I've used the local file URL: file:///tmp/test.ics and ensured that the file is located in /tmp/test.ics but still get the error message that the file could not be imported from the given URL "The URL is not valid, could not download data."
Unfortunately the official url from https://albdonaukreis.buergerportal.digital/calendar/ does not support the download for the locations.

**Comment by KoljaWindeler** [comment]
Nabend, hat Homeassistant denn das Recht auf /tmp zuzugreifen? Da gibt's eine Liste von shared folders oder so in der configuration.yaml

Am einfachsten geht das wirklich die ICs Datei in den www Ordner zu laden und dann via http://ip:8123/local/dateiname.ics  darauf zuzugreifen
Gruss jkw

**Comment by BKneer** [comment]
Ich habe jetzt das ics File in den Folder config kopiert und mit file:///config/Abfallkalender2023.ics eingebunden. Das scheint zu funktionieren. Allerdings bekomme ich diesen Fehler:
2023-02-19 10:13:49.945 ERROR (MainThread) [custom_components.ics.sensor] Traceback (most recent call last):
  File "/config/custom_components/ics/sensor.py", line 188, in get_data
    reoccuring_events = recurring_ical_events.of(cal).between(start_date, end_date)
  File "/usr/local/lib/python3.10/site-packages/recurring_ical_events.py", line 592, in of
    a_calendar = x_wr_timezone.to_standard(a_calendar)
  File "/usr/local/lib/python3.10/site-packages/x_wr_timezone.py", line 153, in to_standard
    timezone = pytz.timezone(timezone)
  File "/usr/local/lib/python3.10/site-packages/pytz/__init__.py", line 188, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'W. Europe Standard Time'

2023-02-19 10:13:49.950 ERROR (MainThread) [custom_components.ics.sensor] 
thanks, Kolja
2023-02-19 10:13:49.953 ERROR (MainThread) [custom_components.ics.sensor] ============= ICS Integration Error ================

**Comment by jose1711** [comment]
what is the content of `TZ` env. variable?
