### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by b10126** [KoljaWindeler/ics#56]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.ics.sensor
Quelle: custom_components/ics/sensor.py:132
Integration: ics (Dokumentation)
Erstmals aufgetreten: 19:05:31 (1470 Vorkommnisse)
Zuletzt protokolliert: 21:07:41

Traceback (most recent call last): File "/config/custom_components/ics/sensor.py", line 181, in get_data _LOGGER.debug(f"fixed {self.check_fix_rrule(cal)} RRule dates") ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/ics/sensor.py", line 155, in check_fix_rrule if("UNTIL" in event["RRULE"]): ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalendar/caselessdict.py", line 89, in __eq__ return self is other or dict(self.items()) == dict(other.items()) ^^^^^^^^^^^ AttributeError: 'str' object has no attribute 'items'

**Comment by b10126** [comment]
any ideas? it is a radicale calendar server which is queried.....

**Comment by jose1711** [comment]
Codebase was updated to use newer icalendar (which is referenced in your error): https://github.com/KoljaWindeler/ics/commit/a677d1c45851186de27be9809b147959e66daa62

I'd retry with an updated version.
