### ISSUE TITLE
Loading of ics failed

### ISSUE THREAD

**Issue by arnoutvw** [KoljaWindeler/ics#8]
I have de following ur:
https://www.kranenburg.de/de/sys/abfallkalender.ics/&r2=A&r3=A&r4=2&r5=2&r6=2&r7=1&r8=1

it worked couple of days ago but now i get this error message:
Traceback (most recent call last): File "/config/custom_components/ics/sensor.py", line 136, in get_data event["END"] = self.check_fix_date_tz(event["DTEND"]) File "/usr/local/lib/python3.7/site-packages/icalendar/caselessdict.py", line 42, in __getitem__ return super(CaselessDict, self).__getitem__(key.upper()) KeyError: 'DTEND'

Also i have gotten an error message in the new ui config that the ics was not valid after reboot that was gone but i still could not get the calendar items

**Comment by KoljaWindeler** [comment]
Hi, thanks for the issue. I can confirm that your calendar doesn't provide end dates .. funny.
I've fixed that in this commit: https://github.com/KoljaWindeler/ics/commit/0903e746c68c916fbc93216a0c4f9b3483753ed9
Kolja
